services:
  - type: web
    name: torqueFlow
    env: docker
    repo: https://github.com/MoeMoola3/TorqueFlow
    branch: develop

    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: obd_analyzer_instance
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: obd_analyzer_instance
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: obd_analyzer_instance
          property: password